# fly.toml app configuration file generated for skyvisor on 2024-04-25T00:02:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'loci-app'
primary_region = 'fra'

[build]
  dockerfile = "Dockerfile"
  build-target = "production"

[env]
  MODE="production"
  APP_ENV="production"
  ENABLE_PPROF=true
  PPROF_PORT=6060
  HTTP_PORT=8000
  RATE_LIMIT_ENABLED=true
  LOG_LEVEL="debug|

  POSTGRES_HOST="localhost"
  POSTGRES_PORT=5454
  POSTGRES_USER="postgres"
  POSTGRES_PASSWORD="postgres"
  POSTGRES_DB="loci-dev"
  JWT_SECRET_KEY="replace_this_with_a_very_strong_random_32_byte_plus_secret_or_deez_nuts"
  JWT_ISSUER="loci"
  JWT_AUDIENCE="loci-app"
  JWT_ACCESS_TOKEN_TTL="15m"
  JWT_REFRESH_TOKEN_TTL="168h"

  # OpenTelemetry Configuration
  OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:4318"
  OTEL_EXPORTER_OTLP_PROTOCOL="http/protobuf"
  OTEL_SERVICE_NAME="loci-templui"
  OTEL_RESOURCE_ATTRIBUTES="service.name=loci-templui,service.version=1.0.0"
  OTEL_LOG_LEVEL="info"
  OTEL_SDK_DISABLED=false

  # Metrics
  METRICS_PORT=9090
  SERVER_PORT=8090

[build.args]
  MODE="production"

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[[services.tls.domains]]
  domain = ""


